<a href="https://colab.research.google.com/github/NIKITACHOKHARIYA/MLP/blob/main/assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np1={'carname':['Alto','i10','bmw'],'color':['red','black','white'],'price':[10,20,30]}
np1

{'carname': ['Alto', 'i10', 'bmw'],
 'color': ['red', 'black', 'white'],
 'price': [10, 20, 30]}

In [ ]:
table=pd.DataFrame(np1)
table

carname  color  price
0    Alto    red     10
1     i10  black     20
2     bmw  white     30

In [ ]:
table.rename(columns={'carname':'car_name'},inplace=True)

In [ ]:
table


car_name  color  price
0     Alto    red     10
1      i10  black     20
2      bmw  white     30

In [ ]:
y=table.drop('price',axis=1)
y

car_name  color
0     Alto    red
1      i10  black
2      bmw  white

In [ ]:
table['year']=(2019,2018,2017)

In [ ]:
table

car_name  color  price  year
0     Alto    red     10  2019
1      i10  black     20  2018
2      bmw  white     30  2017

In [ ]:
x=np.arange(5,50,5)
x

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
aar=np.arange(0,9).reshape(3,3)
aar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
aar.dtype

dtype('int64')

In [ ]:
phone={'phone':[{2345,78455,56899},{45678,455588},{986456,87555}]}
dt1=pd.DataFrame(phone)
dt1

phone
0  {2345, 56899, 78455}
1       {455588, 45678}
2       {986456, 87555}

In [ ]:
dt1['name']=('xyz','abc','mno',
             )
dt1

phone name
0  {2345, 56899, 78455}  xyz
1       {455588, 45678}  abc
2       {986456, 87555}  mno

In [ ]:
five=np.arange(5,25,5)
five

array([ 5, 10, 15, 20])

In [ ]:
np.std(five)


5.5901699437494745

In [ ]:
df=pd.DataFrame({'book_name':["c++","java",'python'],'price':[200,250,100],'adition':[4,2,1]})
df

book_name  price  adition
0       c++    200        4
1      java    250        2
2    python    100        1

In [ ]:
df.rename(columns={'book_name':'BName'},inplace=True)

In [ ]:
df

BName  price  adition
0     c++    200        4
1    java    250        2
2  python    100        1

In [ ]:
df.drop('adition',axis=1)

BName  price
0     c++    200
1    java    250
2  python    100

In [ ]:
nparr=np.array([11,23256,6773,884,905,6,907,90,23,45,99,87,12])
nparr

array([   11, 23256,  6773,   884,   905,     6,   907,    90,    23,
          45,    99,    87,    12])

In [ ]:
nparr.max()

23256

In [ ]:
nparr.min()

6

In [ ]:
nptable=pd.DataFrame({'Id':[121,45,774,85],'name':['ishan','nikita','viraj','naman'],'c++':[90,84,85,74]})
nptable

Id    name  c++
0  121   ishan   90
1   45  nikita   84
2  774   viraj   85
3   85   naman   74

In [ ]:
fmat=np.arange(0,25).reshape(5,5)
fmat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
fmat.shape

(5, 5)

In [ ]:
fmat.size

25

In [ ]:
mobile=pd.DataFrame({'owner':['abc','xyz','john'],'city':['jamnagar','rajkot','surat'],'number':[45788,7856,9658]})
mobile

owner      city  number
0   abc  jamnagar   45788
1   xyz    rajkot    7856
2  john     surat    9658

In [ ]:
mobile['year']=[2019,2014,2003]
mobile

owner      city  number  year
0   abc  jamnagar   45788  2019
1   xyz    rajkot    7856  2014
2  john     surat    9658  2003

In [ ]:
# prompt: Create a NumPy array using random function?
lst=[]
for i in range(5):
  rdar=np.random.randint(1,20)
  lst.append(rdar)
lst

[7, 15, 10, 12, 5]

In [ ]:
np.average(lst)

9.8