<a href="https://colab.research.google.com/github/NIKITACHOKHARIYA/MLP/blob/main/Knieighbor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
iri=pd.read_csv('/content/iris.csv')
iri.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
X=iri.drop('variety',axis=1)
#In this case, axis=1 indicates that the columns should be dropped.
#If axis is not specified, it defaults to 0, which means rows would be dropped.
X.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [5]:
Y=iri['variety']
Y.value_counts()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
Y=label.fit_transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
from sklearn.model_selection import train_test_split
#X_train_X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
clss_knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski')
#n_neighbors=5: This argument specifies the number of nearest neighbors to use when classifying a data poin
#metric='minkowski',the distance metric to use when calculating the distance between data points

In [19]:
clss_knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [21]:
pred_knn=clss_knn.predict(X_test)
pred_knn

array([2, 1, 1, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0, 2, 0, 1, 2, 2, 0, 2, 2,
       2, 1, 1, 2, 0, 0, 1, 2])

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,pred_knn)

array([[ 7,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 10]])

In [25]:
clss_knn.score(X_test,Y_test)

0.9666666666666667

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(pred_knn,Y_test)

0.9666666666666667

In [28]:
from sklearn.naive_bayes import GaussianNB
class_nb=GaussianNB()
class_nb.fit(X_train,Y_train)

GaussianNB()

In [30]:
pred=class_nb.predict(X_test)

In [31]:
pred

array([2, 1, 1, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0, 2, 0, 1, 2, 2, 0, 2, 2,
       2, 1, 1, 1, 0, 0, 1, 2])

In [32]:
confusion_matrix(Y_test,pred)

array([[ 7,  0,  0],
       [ 0, 12,  1],
       [ 0,  1,  9]])

In [33]:
class_nb.score(X_test,Y_test)

0.9333333333333333