<a href="https://colab.research.google.com/github/NIKITACHOKHARIYA/Cricknight/blob/main/lec_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello Ml")

hello Ml


In [ ]:
a=[7,5,6]

In [ ]:
print(type(a))

<class 'list'>


In [ ]:
import numpy as np

In [ ]:
b=np.array([7,5,6])

In [ ]:
b

array([7, 5, 6])

In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
print(b.ndim)

1


In [ ]:
c=np.array([[[2,3,4]]])
print(c.ndim)

3


In [ ]:
c[0][0]


array([2, 3, 4])

In [ ]:
x=np.array(1,int)
x

array(1)

In [ ]:
y=np.array([1,2,3],)
print(y.itemsize)

8


In [ ]:
y


array([1, 2, 3])

In [ ]:
n=np.array([[1,2],[4,5],[6,7,]],)
print(n)
print(n.ndim)
print(n.size)
print(n.itemsize)
print(n.dtype)
print(n.shape)

[[1 2]
 [4 5]
 [6 7]]
2
6
8
int64
(3, 2)


In [ ]:
print(n.dtype)

int64


In [ ]:
z=np.array([[[1,2.5],['n',4]]])
print(z)
print(z.ndim)
print(z.dtype)
print(z.itemsize)
print(z.size)
print(z.shape)

[[['1' '2.5']
  ['n' '4']]]
3
<U32
128
4
(1, 2, 2)


In [ ]:
a=np.zeros((3,3),)
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
mat=np.array([[1,2],[3,4],[5,6]],)
mat


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
ar4=np.arange(12)
ar4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
ar5=np.arange(5,15)
ar5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
ar5.size

10

In [ ]:
ar5.ndim

1

In [ ]:
mat.ndim

2

In [ ]:
ar5.dtype

dtype('int64')

In [ ]:
type(ar5)

numpy.ndarray

In [ ]:
ar6=np.arange(5,15,3).reshape(2,2)
ar6

array([[ 5,  8],
       [11, 14]])

In [ ]:
ar7=np.arange(2,11,1).reshape(3,3)
ar7

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
ar8=np.arange(33,59,3).reshape(3,3)
ar8


array([[33, 36, 39],
       [42, 45, 48],
       [51, 54, 57]])

In [ ]:
ar8[1][2]

48

In [ ]:
ar9=np.arange(5,126,5).reshape(5,5)
ar9

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125]])

In [ ]:
a10=np.arange(1,101,2)
a10


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
even=np.arange(2,101,2)
even

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
even[24:35] #slicing

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70])

In [ ]:
a12=np.arange(7,106,7)
a12

array([  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
        98, 105])

In [ ]:
a13=np.linspace(1,50,6)
a13

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [ ]:
print(even[9])#index

20


In [ ]:
even[-1]

100

In [ ]:
mat=np.arange(9).reshape(3,3)
mat


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
mat1=np.arange(10,19).reshape(3,3)
mat1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
mat3=np.hstack((mat,mat1))
mat3

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [ ]:
mat4=np.vstack((mat,mat1))
mat4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
mat3.ndim

2

In [ ]:
mat3.shape

(3, 7)

In [ ]:
mat4.shape

(6, 3)

In [ ]:
mat5=np.hsplit(mat3,2)
mat5

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [ ]:
mat6=np.vsplit(mat4,2)
mat6

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [ ]:
mat7=np.vsplit(mat4,(2,5))
mat7

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18]])]

In [ ]:
mat8=np.vsplit(mat4,(2,4,5))
mat8

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]